module ChatApp {
  interface ChatCallback {
    void callback(in string message);
  };
  interface Chat {
    string join(in ChatCallback objref, in string nickname);
    void post(in ChatCallback objref, in string nickname, in string msg);
    void list(in ChatCallback objref, in string nickname);
    void leave(in ChatCallback objref, in string nickname);
   
    void play(in ChatCallback objref, in string nickname, in string color);
    void put(in ChatCallback objref, in string nickname, in string pos);   
    void leaveGame( in string nickname);
  };
  interface GameCallback {
    void boardupdate(in char[][] gb);
  };
  interface Game {
    boolean join(in ChatCallback chatref, in GameCallback gbref, in string nickname, in char colour);
    boolean makemove(in ChatCallback chatref, in string nickname, in string move);
    void passturn();
    void list(in ChatCallback chatref);
    void leave(in ChatCallback chatref, in string nickname);
    void reset(in boolean manReset);

  };
};
 
